### PR TITLE
Setting up Flask Project Structure

### PR DESCRIPTION
**Pull request by Bonifaze**
@Wandji69  this is Bovimacoco
- This pull request sets up the initial Flask project structure, including file organization, routing, configuration, and dependencies For Windows.
- Added a virtual environment setup 
Screenshot 2024-11-18 142953

- Please review the overall structure and any configuration suggestions.

## Related Task/Issue
- Fixes task T379991 (or related task).

## Notes for Reviewers
Screenshot 2024-11-18 142924

- Please check the file structure and ensure the setup aligns with the project's requirements.

### CODE REVIEW

**Comment by Wandji69** [comment]
Thank you for this @Bonifaze, Please comment on the task on Phabricator, and also add a link there, that's a better way to track this. I would also love to know if you claimed the task on Phabricator as well

**Comment by Wandji69** [comment]
@Bonifaze, we are building an API, so submitting a .venv file to GitHub isn't good practice. That's a lot of files. You can rather create a requirement.txt from which dependencies will be installed. Also, add a git ignore file to help you with this.

**Comment by Bonifaze** [comment]
> Thank you for this @Bonifaze, Please comment on the task on Phabricator, and also add a link there, that's a better way to track this. I would also love to know if you claimed the task on Phabricator as well

@Wandji69 Please which link should i add to the Phabricator, yes i claimed the task too

**Comment by Bonifaze** [comment]
> @Bonifaze, we are building an API, so submitting a .venv file to GitHub isn't good practice. That's a lot of files. You can rather create a requirement.txt from which dependencies will be installed. Also, add a git ignore file to help you with this.

@Wandji69 Are you saying if i remove the .venv file from github the task is done. i can submit it as done?

**Comment by Wandji69** [comment]
> > Thank you for this @Bonifaze, Please comment on the task on Phabricator, and also add a link there, that's a better way to track this. I would also love to know if you claimed the task on Phabricator as well
> 
> @Wandji69 Please which link should i add to the Phabricator, yes i claimed the task too

Yes the link to this PR

**Comment by Wandji69** [comment]
> > @Bonifaze, we are building an API, so submitting a .venv file to GitHub isn't good practice. That's a lot of files. You can rather create a requirement.txt from which dependencies will be installed. Also, add a git ignore file to help you with this.
> 
> @Wandji69, Are you saying that if I remove the .venv file from GitHub, the task is done, and I can submit it as done?

Remove the .venv and that should be it for now.

**Comment by Bonifaze** [comment]
> > > @Bonifaze, we are building an API, so submitting a .venv file to GitHub isn't good practice. That's a lot of files. You can rather create a requirement.txt from which dependencies will be installed. Also, add a git ignore file to help you with this.
> > 
> > 
> > @Wandji69, Are you saying that if I remove the .venv file from GitHub, the task is done, and I can submit it as done?
> 
> Remove the .venv and that should be it for now.

@Wandji69 
I have Removed it. Thank you. So can i now fill the form that i have completed the task

**Comment by eugeneegbe** [comment]
@Bonifaze are you still working on minimizing this? It looks a bit huge.

**Pull request closed without merging**
